### ISSUE TITLE
Plugin not working.....?

### ISSUE THREAD

**Issue by Hu5ker** [xxyy/commandblockerultimate#14]
config file of the plugin has been modified. ProtocolLib is installed too. When I type "/" and then I press tab, I still get a list of commands. When I type /?, /plugins and /help I get the default error message:

![error 1](http://ts3.mineverso.com/recursos/IMG/borrar/error--cbu-001.png)

This is the config.yml, but, as you can see I already translate it:

![error 2](http://ts3.mineverso.com/recursos/IMG/borrar/error--cbu-002.png)

When I use /cbu reloadcfg this is what the console says:

![error 3](http://ts3.mineverso.com/recursos/IMG/borrar/error--cbu-003.png)

Server currently using spigot 1.8

**Comment by xxyy** [comment]
Hi, thanks for your detailed bug report!

This looks like some strange behaviour. Does it work if you restart the
server instead of reloading the configuration file?

Also, I don't quite understand if you have a problem with tab complete - is
it not working for you or did you just mention it to show that the rest of
the plugin is working?

-- Above message was sent from my mobile phone. There may and will be all
kinds of errors included.

**Comment by Hu5ker** [comment]
Yes, doing cbu reloadcfg and then restarting the server solve's the problem, in part.

What I mean with the tab is that you type "/" in the game and then press tab key and a list of commands of all plugins appears. I want to block this. In the plugin version for spigot 1.7 this was block by default(as far I remember). What should I do?.

Regards!.

**Comment by xxyy** [comment]
So you want to block all tab completion?

**Comment by xxyy** [comment]
Hi @Hu5ker, is this still an issue for you? If yes, could you outline your issue more clearly?

**Comment by xxyy** [comment]
Reopen this ticket or create a new one if you still have issues with the plugin.
