### ISSUE TITLE
List of all permissions?

### ISSUE THREAD

**Issue by FrankHeijden** [xxyy/commandblockerultimate#33]
Heya,
where can i find a list of all permissions? cant find them anywhere :(

**Comment by xxyy** [comment]
Heya, there is no list, because there are only two: [`cmdblock.admin`](https://github.com/xxyy/commandblockerultimate/blob/ff9df305bb542ec5b52c876808c8fbcead9db17b/spigot/src/main/resources/plugin.yml#L13) for usage of the /cbu or /gcbu commands, and [`cmdblock.bypass`](https://github.com/xxyy/commandblockerultimate/blob/ff9df305bb542ec5b52c876808c8fbcead9db17b/spigot/src/main/resources/config.yml#L11) to be able to use all blocked commands. You can configure the latter in the configuration file.
