### ISSUE TITLE
Multiple Messages

### ISSUE THREAD

**Issue by Clydark** [xxyy/commandblockerultimate#35]
Hello for certain commands the no permission commands spam twice.

For example:

/<script>.js
//setbiome

and more.

If you'd like me to get in contact with you to show you the exact issue then just let me know.

**Comment by xxyy** [comment]
Hi, thanks for reporting this issue.

Could you please describe more in detail what you were doing, what
happened, and what you would like to see instead? A screenshot of the
displayed messages could be helpful.

Does the issue only appear with WorldEdit commands, or are other plugins
affected as well?

**Comment by Clydark** [comment]
I've only tested with worldedit commands and I think it has something to do with the double / or the weird characters like /< being next to each other. Another thing might be that when a command has two ways to be used, for example I can do /setbiome and one no permission message will pop up but if I do //setbiome, which does the same thing, it'll spam twice.


Here's some screenshots
===================
http://i.imgur.com/Gx14QgV.png

I don't know what commands actually do this but I believe there is some sort of trend they follow.

**Comment by Clydark** [comment]
//setbiome doesn't spam twice I was wrong

**Comment by xxyy** [comment]
Fascinating. Interested why it would do that, lol. Could you provide your
platform (Bungee or Spigot), server version, plugin version, and plugins
list? Are there any messages in the console starting with [CBU] or
[CommandBlockerUltimate]?

**Comment by Clydark** [comment]
Platform: Spigot 1.12.1
Server Version: ?? No clue what you mean
Plugin Version: 1.5.2
Plugin List:
- CommandBlockerUltimate-1.5.2
- EssentialsX-2.0.1
- EssentialsXChat-2.0.1
- FastAsyncWorldEdit-bukkit-17.08.04-1186ca8-791-14.1.22
- Multiverse-Core-2.5
- PermissionsEx-1.23.4
- ProtocolLib
- Vault
- worldedit-bukkit-6.1.7.2
- worldguard-6.2.1

Messages in console with CBU:
[16:31:08 INFO]: [CBU] Enabling CommandBlockerUltimate v1.5.2
[16:31:08 WARN]: [CBU] It is recommended that you install Yamler, because that allows the config to be a lot more flexible and straightforward to use.
[16:31:09 WARN]: [CBU] Using the simplified configuration adapter! When CommandBlockerUltimate updates, new options won't be in your configuration file!
[16:31:09 INFO]: [CBU] CommandBlockerUltimate cbu-bootstrap Version 1.5.2 Build 5cc5f51 is licensed under the GNU General Public License Version 2. See the LICENSE file included in its .jar archive for details.

**Comment by xxyy** [comment]
I've been able to reproduce the issue locally. Would've been great to know that the way to block the command is via its `/cs` alias. I'll be taking a look at what happens exactly.

**Comment by xxyy** [comment]
Interestingly enough, the command event is fired twice for that command. With a quick look at the WorldEdit source, I have been unable to figure out why so far. However, since you have PermissionsEx installed, you could also block the command by removing the `worldedit.scripting.execute` (`-worldedit.scripting.execute`) permission from the players you want to block from executing the command

**Comment by xxyy** [comment]
Okay, this seems to be related to how WorldEdit translates `/<script>.js` to `/cs <script>.js`...

Weirdly enough, they first [change the message to `/cs <script>.js`](https://github.com/sk89q/WorldEdit/blob/master/worldedit-core/src/main/java/com/sk89q/worldedit/extension/platform/CommandManager.java#L199), and then [re-fire the event as if nothing happened](https://github.com/sk89q/WorldEdit/blob/master/worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/WorldEditListener.java#L91) - which ends up in the event being fired twice.

It seems that they're doing this so that other plugins (such as CBU) can react to the changed command. Sadly, the reason is not documented on their side.

I have found a workaround (ignoring already-cancelled events, assuming that we can't do anything against these anyways). This may mean that other plugins which do their own command handling but aren't as friendly as WorldEdit may no longer be blocked.

Please download [this](https://ci.l1t.li/job/public~cmdblkult/64/) updated development build and report back on whether it fixes your issue.

**Comment by Clydark** [comment]
Thank you so much really appreciate the effort.

**Comment by Clydark** [comment]
The reason I didn't disable it in permissionsex is because the no permission message would be different, I wanted them all to be the same.

**Comment by Clydark** [comment]
When I do the command /<script>.js it only spams once now, thanks so much really great plugin.

**Comment by Clydark** [comment]
I'll let you know if any other commands come up.
